In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_breast_cancer                

from sklearn.model_selection import train_test_split    

breastCancer = load_breast_cancer()

breastCancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
print(breastCancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [4]:
print( type(breastCancer.data) )
print( breastCancer.data.shape )
X = breastCancer.data

<class 'numpy.ndarray'>
(569, 30)


In [5]:
print( type(breastCancer.target) )
print( breastCancer.target.shape )
y = breastCancer.target

<class 'numpy.ndarray'>
(569,)


In [6]:
from sklearn.model_selection import train_test_split    

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [7]:
X_train.shape

(426, 30)

In [8]:
y_train.shape

(426,)

In [9]:
np.bincount(y_train)

array([159, 267], dtype=int64)

In [10]:
np.bincount(y_train) / y_train.shape[0]

array([0.37323944, 0.62676056])

In [11]:
X_test.shape

(143, 30)

In [12]:
y_test.shape

(143,)

In [13]:
np.bincount(y_test)

array([53, 90], dtype=int64)

In [14]:
np.bincount(y_test)/y_test.shape[0]

array([0.37062937, 0.62937063])

In [15]:
from sklearn.svm import LinearSVC

In [16]:
svm = LinearSVC(max_iter = 10000000)

In [17]:
svm.fit(X_train, y_train)

C:\Users\Joaquin Llenado\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(max_iter=10000000)

In [18]:
print("The prediction by the model for the first case in the testing data:")
print( svm.predict(X_test[:1]) )

print("The true labels of the first case in the testing dataset:")
print(y_test[:1])

The prediction by the model for the first case in the testing data:
[0]
The true labels of the first case in the testing dataset:
[0]


In [19]:
n=4
print("The prediction by the model for the", n, "th case in the testing data:")
print( svm.predict(X_test[n-1:n]) )

print("The true labels of the", n, "th case in the testing data:")
print(y_test[n-1:n])

The prediction by the model for the 4 th case in the testing data:
[1]
The true labels of the 4 th case in the testing data:
[1]


In [20]:
print("The predictions by the model for the first 16 cases in the testing data:")
print( svm.predict(X_test[:16]) )

print("The true labels of the first 16 cases in the testing dataset:")
print(y_test[:16])

The predictions by the model for the first 16 cases in the testing data:
[0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0]
The true labels of the first 16 cases in the testing dataset:
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]


In [21]:
n=16
print("The predictions by the model for the first", n,  "cases in the testing data:")
print( svm.predict(X_test[:n]) )

print("The true labels of the first", n,  "cases in the testing data:")
print(y_test[:n])

The predictions by the model for the first 16 cases in the testing data:
[0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0]
The true labels of the first 16 cases in the testing data:
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]


In [22]:
print("The predictions by the model for all the cases in the testing data:")
print( svm.predict(X_test) )

print("The true labels of all the cases in the testing data:")
print(y_test)

The predictions by the model for all the cases in the testing data:
[0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 1 1
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0]
The true labels of all the cases in the testing data:
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0]


In [23]:
predictedResults = svm.predict(X_test)
boolMaskOfWrongCases = (predictedResults != y_test)

print("Wrong predictions out of 143 testing cases:\n", predictedResults[boolMaskOfWrongCases]  )

print("The true corrsponding labels:\n", y_test[boolMaskOfWrongCases]) 

print("The number of wrongly predicted cases is ", boolMaskOfWrongCases.sum() )

print("The accuracy of prediction is ", 1- boolMaskOfWrongCases.sum()/450 )

Wrong predictions out of 143 testing cases:
 [0 0 0 1 0]
The true corrsponding labels:
 [1 1 1 0 1]
The number of wrongly predicted cases is  5
The accuracy of prediction is  0.9888888888888889


In [24]:
predictedResults = svm.predict(X_test)
boolMaskOfWrongCases = (predictedResults != y_test)

print("Wrong predictions out of 143 testing cases:\n", predictedResults[boolMaskOfWrongCases]  )

print("The true corrsponding labels:\n", y_test[boolMaskOfWrongCases]) 

print("The number of wrongly predicted cases is ", boolMaskOfWrongCases.sum() )

print("The accuracy of prediction is ", 1- boolMaskOfWrongCases.sum()/450 )

Wrong predictions out of 143 testing cases:
 [0 0 0 1 0]
The true corrsponding labels:
 [1 1 1 0 1]
The number of wrongly predicted cases is  5
The accuracy of prediction is  0.9888888888888889


In [25]:
print("The accuracy of prediction on the testing dataset is ",  svm.score(X_test, y_test))


The accuracy of prediction on the testing dataset is  0.965034965034965


In [26]:
print("The accuracy of prediction on the training dataset is ",  svm.score(X_train, y_train))
print("But this is NOT a reliable indicator of effectiveness, and tends to be too good.")


The accuracy of prediction on the training dataset is  0.9647887323943662
But this is NOT a reliable indicator of effectiveness, and tends to be too good.


In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf = RandomForestClassifier()

In [29]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [30]:
predictedResults = rf.predict(X_test)
boolMaskOfWrongCases = (predictedResults != y_test)

print("Wrong predictions out of 143 testing cases:\n", predictedResults[boolMaskOfWrongCases]  )

print("The true corrsponding labels:\n", y_test[boolMaskOfWrongCases]) 

print("The number of wrongly predicted cases is ", boolMaskOfWrongCases.sum() )

print("The accuracy of prediction is ", 1- boolMaskOfWrongCases.sum()/450 )

Wrong predictions out of 143 testing cases:
 [0 0 0 1]
The true corrsponding labels:
 [1 1 1 0]
The number of wrongly predicted cases is  4
The accuracy of prediction is  0.9911111111111112


In [31]:
print("The accuracy of RF prediction on the testing dataset is ",  rf.score(X_test, y_test))

The accuracy of RF prediction on the testing dataset is  0.972027972027972


In [32]:
print("The accuracy of RF prediction on the training dataset is ",  rf.score(X_train, y_train))
print("But this is NOT a reliable indicator of effectivenss, and tends to be too good.")

The accuracy of RF prediction on the training dataset is  1.0
But this is NOT a reliable indicator of effectivenss, and tends to be too good.


In [33]:
# Visit https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
#  examine the example there to see how you may import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

In [34]:
# Visit https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
#  examine the example there to see how you may instantiate a KNeighborsClassifier object
knc = KNeighborsClassifier()

In [35]:
knc.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
predictedResults = knc.predict(X_test)
boolMaskOfWrongCases = (predictedResults != y_test)

print("Wrong predictions out of 143 testing cases:\n", predictedResults[boolMaskOfWrongCases]  )

print("The true corrsponding labels:\n", y_test[boolMaskOfWrongCases]) 

print("The number of wrongly predicted cases is ", boolMaskOfWrongCases.sum() )

print("The accuracy of prediction is ", 1- boolMaskOfWrongCases.sum()/450 )

Wrong predictions out of 143 testing cases:
 [0 0 0 1 0 1 1 0 1]
The true corrsponding labels:
 [1 1 1 0 1 0 0 1 0]
The number of wrongly predicted cases is  9
The accuracy of prediction is  0.98


In [37]:
print("The accuracy of KNeighborsClassifier prediction on the testing dataset is ",  knc.score(X_test, y_test))

The accuracy of KNeighborsClassifier prediction on the testing dataset is  0.9370629370629371


In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
gNB = GaussianNB()

In [40]:
gNB.fit(X_train, y_train)

GaussianNB()

In [41]:
predictedResults = gNB.predict(X_test)
boolMaskOfWrongCases = (predictedResults != y_test)

print("Wrong predictions out of 143 testing cases:\n", predictedResults[boolMaskOfWrongCases]  )

print("The true corrsponding labels:\n", y_test[boolMaskOfWrongCases]) 

print("The number of wrongly predicted cases is ", boolMaskOfWrongCases.sum() )

print("The accuracy of prediction is ", 1- boolMaskOfWrongCases.sum()/450 )

Wrong predictions out of 143 testing cases:
 [0 0 0 1 0 1 1 1 1]
The true corrsponding labels:
 [1 1 1 0 1 0 0 0 0]
The number of wrongly predicted cases is  9
The accuracy of prediction is  0.98


In [42]:
print("The accuracy of Gaussian Naive Bayes prediction on the testing dataset is ",  gNB.score(X_test, y_test))

The accuracy of Gaussian Naive Bayes prediction on the testing dataset is  0.9370629370629371
